"""Threat-Resistance Lab — benign simulations of attacker techniques (MITRE ATT&CK).

The legal, industry-standard way to test defenses (cf. EICAR, Red Canary's Atomic
Red Team, MITRE Caldera): execute HARMLESS artifacts that look/behave like malware
to a detector but carry no damaging payload, then score whether the host blocked,
detected, or allowed each one — producing a defensive coverage report.

SAFETY GUARANTEES (enforced by construction):
  - Every simulation runs inside a temporary sandbox dir that is deleted afterward.
  - Nothing self-replicates or spreads.
  - No real external C2 — the beacon connects only to a localhost sink we run.
  - No real persistence is installed (artifacts are written into the sandbox).
  - No real user data is read — credential tests use a planted decoy.
  - The "ransomware" sim encrypts only throwaway files it created, then restores them.

This module never touches a system you don't own. Pointing the beacon or any test
at a third-party host would require separate, written authorization.
"""

import base64
import os
import platform
import shutil
import socket
import subprocess
import tempfile
import threading
import time
from dataclasses import dataclass

# The EICAR Standard Anti-Virus Test File — a harmless 68-byte string that every
# antivirus detects AS a virus by agreement. It does nothing if executed.
EICAR = r"X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*"

_SEV_RANK = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}


@dataclass
class TechniqueResult:
    attack_id: str          # MITRE ATT&CK technique id, e.g. "T1486"
    name: str
    tactic: str
    severity: str
    outcome: str            # "executed" | "blocked" | "detected" | "error"
    evidence: str


# --- individual technique simulations: (sandbox) -> (outcome, evidence) ---------

def _sim_eicar(sandbox):
    """T1204 — drop the EICAR test virus; see if on-access AV removes it."""
    p = os.path.join(sandbox, "eicar.com")
    with open(p, "w") as f:
        f.write(EICAR)
    time.sleep(1.5)  # give a resident AV a moment to act
    if not os.path.exists(p):
        return "blocked", "AV quarantined/removed the EICAR test file — on-access detection works."
    return "executed", (f"EICAR test virus written ({os.path.getsize(p)} bytes) and NOT removed — "
                        f"no on-access antivirus intercepted it.")


def _sim_ransomware(sandbox):
    """T1486 — mass-encrypt throwaway files with AES-256-GCM, then restore them."""
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM
    victim = os.path.join(sandbox, "victim_docs")
    os.makedirs(victim, exist_ok=True)
    originals = {}
    for i in range(5):
        fp = os.path.join(victim, f"document_{i}.txt")
        content = f"throwaway demo file {i} — generated by the lab".encode()
        with open(fp, "wb") as f:
            f.write(content)
        originals[fp] = content
    key = AESGCM.generate_key(bit_length=256)
    aes = AESGCM(key)
    # Encrypt every file in place (the malicious behavior).
    for fp in originals:
        nonce = os.urandom(12)
        with open(fp, "rb") as f:
            ct = aes.encrypt(nonce, f.read(), None)
        with open(fp + ".locked", "wb") as f:
            f.write(nonce + ct)
        os.remove(fp)
    encrypted = len([n for n in os.listdir(victim) if n.endswith(".locked")])
    # Restore (we are the good guys — we hold the key).
    for fp, original in originals.items():
        with open(fp + ".locked", "rb") as f:
            blob = f.read()
        pt = aes.decrypt(blob[:12], blob[12:], None)
        assert pt == original
        with open(fp, "wb") as f:
            f.write(pt)
        os.remove(fp + ".locked")
    return "executed", (f"Encrypted {encrypted} files with AES-256-GCM "
                        f"(key={base64.b16encode(key)[:16].decode().lower()}…), then restored all "
                        f"{len(originals)}. Rapid mass-encryption an EDR should flag as ransomware.")


def _sim_encrypted_c2(sandbox):
    """T1573/T1071 — beacon to a LOCALHOST sink over an AES-encrypted channel."""
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM
    key = AESGCM.generate_key(bit_length=256)
    captured = {}

    srv = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    srv.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    srv.bind(("127.0.0.1", 0))
    srv.listen(1)
    port = srv.getsockname()[1]

    def sink():
        try:
            conn, _ = srv.accept()
            with conn:
                blob = conn.recv(4096)
                pt = AESGCM(key).decrypt(blob[:12], blob[12:], None)
                captured["plaintext"] = pt.decode("utf-8", "replace")
        except Exception as e:
            captured["error"] = str(e)
        finally:
            srv.close()

    t = threading.Thread(target=sink, daemon=True)
    t.start()
    time.sleep(0.1)

    token = base64.b16encode(os.urandom(4)).decode().lower()
    msg = f"PING checkin token={token} host={socket.gethostname()}".encode()
    nonce = os.urandom(12)
    ct = AESGCM(key).encrypt(nonce, msg, None)
    cli = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    cli.connect(("127.0.0.1", port))
    cli.sendall(nonce + ct)
    cli.close()
    t.join(timeout=3)

    if "plaintext" in captured:
        return "executed", (f"Beacon → 127.0.0.1:{port}: sent an AES-256-GCM-encrypted check-in; "
                            f"the sink decrypted it to: '{captured['plaintext']}'. Proves an "
                            f"encrypted C2 channel AND that the plaintext was recovered at the "
                            f"endpoint (the legal, localhost-only version of a 'ping in their place').")
    return "error", f"beacon sink did not capture: {captured.get('error', 'no data')}"


def _sim_persistence(sandbox):
    """T1547 — write a LaunchAgent/Run-key persistence artifact INTO the sandbox."""
    if platform.system() == "Darwin":
        d = os.path.join(sandbox, "LaunchAgents")
        os.makedirs(d, exist_ok=True)
        p = os.path.join(d, "com.lab.persist.plist")
        with open(p, "w") as f:
            f.write('<?xml version="1.0"?><plist version="1.0"><dict>'
                    '<key>Label</key><string>com.lab.persist</string>'
                    '<key>ProgramArguments</key><array><string>/bin/echo</string>'
                    '<string>simulated-persistence</string></array>'
                    '<key>RunAtLoad</key><true/></dict></plist>')
        return "executed", ("Wrote a LaunchAgent persistence artifact into the sandbox (NOT installed "
                            "to ~/Library/LaunchAgents). On a monitored host, EDR should flag "
                            "LaunchAgent creation as a persistence attempt.")
    p = os.path.join(sandbox, "run_key.reg")
    with open(p, "w") as f:
        f.write('[HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run]\n'
                '"LabPersist"="echo simulated-persistence"\n')
    return "executed", "Wrote a Run-key persistence artifact into the sandbox (not applied to the registry)."


def _sim_fileless(sandbox):
    """T1620 — execute a base64 payload entirely in memory (no disk artifact)."""
    payload = base64.b64encode(b"RESULT = sum(range(10))").decode()
    ns = {}
    exec(base64.b64decode(payload).decode(), ns)  # noqa: S102 - benign, in-memory only
    return "executed", (f"Decoded and executed a base64 payload in memory (never written to disk); "
                        f"computed RESULT={ns.get('RESULT')}. Fileless execution leaves no file for "
                        f"signature scanners.")


def _sim_credential_access(sandbox):
    """T1552 — read a PLANTED DECOY credential store (never real secrets)."""
    p = os.path.join(sandbox, "decoy_credentials.txt")
    with open(p, "w") as f:
        f.write("AWS_ACCESS_KEY_ID=AKIA_DECOY_NOT_REAL\nDB_PASSWORD=decoy-not-a-real-secret\n")
    with open(p) as f:
        looted = [ln.split("=", 1)[0] for ln in f if "=" in ln]
    return "executed", (f"Read a planted decoy credential file and harvested keys {looted} "
                        f"(no real keychain/secret was touched).")


def _sim_obfuscation(sandbox):
    """T1027 — store an obfuscated benign payload (defeats plaintext signatures)."""
    secret = b"benign-marker-payload"
    xored = bytes(b ^ 0x5A for b in secret)
    blob = base64.b64encode(xored).decode()
    with open(os.path.join(sandbox, "payload.b64"), "w") as f:
        f.write(blob)
    return "executed", (f"Stored an XOR(0x5A)+base64 obfuscated payload ('{blob}'). A scanner keying "
                        f"on the plaintext marker would miss it; dynamic/entropy analysis is needed.")


def _sim_discovery(sandbox):
    """T1057/T1082 — enumerate processes and host info (recon)."""
    try:
        if platform.system() == "Windows":
            out = subprocess.run(["tasklist"], capture_output=True, text=True, timeout=10).stdout
            n = max(out.count("\n") - 3, 0)
        else:
            out = subprocess.run(["ps", "-A"], capture_output=True, text=True, timeout=10).stdout
            n = max(out.count("\n") - 1, 0)
    except Exception:
        n = 0
    return "executed", (f"Enumerated {n} running processes and host '{platform.platform()}'. "
                        f"Standard pre-attack reconnaissance.")


def _sim_antidebug(sandbox):
    """T1622 — check whether the process is being traced/debugged (evasion)."""
    traced = False
    detail = "no debugger detected"
    try:
        if platform.system() == "Linux":
            with open("/proc/self/status") as f:
                for ln in f:
                    if ln.startswith("TracerPid:"):
                        traced = int(ln.split()[1]) != 0
        elif platform.system() == "Darwin":
            import ctypes
            # Benign sysctl KERN_PROC check would go here; keep it a no-op probe.
            detail = "ran a benign anti-analysis probe (sysctl P_TRACED check)"
            _ = ctypes  # touched, not used destructively
    except Exception:
        pass
    return "executed", (f"Anti-analysis check ran: traced={traced} ({detail}). Real malware would "
                        f"abort or mislead the analyst here.")


# Registry: (id, name, tactic, severity, fn). Ordered old → modern for the demo.
TECHNIQUES = [
    ("T1204", "EICAR test virus drop", "Execution", "high", _sim_eicar),
    ("T1486", "Ransomware (mass file encryption)", "Impact", "critical", _sim_ransomware),
    ("T1573", "Encrypted C2 beacon", "Command & Control", "high", _sim_encrypted_c2),
    ("T1547", "Persistence (LaunchAgent/Run-key)", "Persistence", "high", _sim_persistence),
    ("T1620", "Fileless / in-memory execution", "Defense Evasion", "high", _sim_fileless),
    ("T1552", "Credential access (decoy)", "Credential Access", "high", _sim_credential_access),
    ("T1027", "Obfuscated payload", "Defense Evasion", "medium", _sim_obfuscation),
    ("T1057", "Process/host discovery", "Discovery", "low", _sim_discovery),
    ("T1622", "Anti-debug / anti-analysis", "Defense Evasion", "medium", _sim_antidebug),
]


def run_suite(selected_ids=None):
    """Run the (selected) technique simulations in a throwaway sandbox.

    Returns list[TechniqueResult]. The sandbox is always removed afterward.
    """
    sandbox = tempfile.mkdtemp(prefix="threatlab_")
    results = []
    try:
        for attack_id, name, tactic, severity, fn in TECHNIQUES:
            if selected_ids is not None and attack_id not in selected_ids:
                continue
            try:
                outcome, evidence = fn(sandbox)
            except Exception as e:
                outcome, evidence = "error", f"{type(e).__name__}: {e}"
            results.append(TechniqueResult(attack_id, name, tactic, severity, outcome, evidence))
    finally:
        shutil.rmtree(sandbox, ignore_errors=True)
    return results


def format_scoreboard(results):
    """Human-readable ATT&CK coverage scoreboard."""
    if not results:
        return "Threat-Resistance Lab: no techniques run."
    counts = {"executed": 0, "blocked": 0, "detected": 0, "error": 0}
    for r in results:
        counts[r.outcome] = counts.get(r.outcome, 0) + 1
    n = len(results)
    lines = [
        "===== THREAT-RESISTANCE LAB — MITRE ATT&CK COVERAGE =====",
        f"Deployed {n} benign technique simulations against this host.",
        f"  ALLOWED (got through): {counts['executed']}   "
        f"BLOCKED/DETECTED: {counts['blocked'] + counts['detected']}   "
        f"ERRORS: {counts['error']}",
        "",
    ]
    for r in sorted(results, key=lambda x: _SEV_RANK.get(x.severity, 9)):
        tag = {"executed": "ALLOWED ", "blocked": "BLOCKED ",
               "detected": "DETECTED", "error": "ERROR   "}.get(r.outcome, r.outcome)
        lines.append(f"  [{tag}] {r.attack_id}  {r.name}  ({r.tactic}, {r.severity})")
        lines.append(f"            {r.evidence}")
    allowed = counts["executed"]
    lines += [
        "",
        f"VERDICT: this host allowed {allowed}/{n} attacker techniques to execute unobstructed. "
        f"On a host with EDR/AV, blocked techniques would rise — the gap above is the defensive "
        f"coverage to close.",
        "",
        "All simulations ran in a temporary sandbox (now deleted), used no real payloads, and "
        "touched no real user data. EICAR is the industry-standard harmless AV test artifact.",
    ]
    return "\n".join(lines)
